package com.yerayyas.chatappkotlinproject.data.model

import com.google.firebase.database.IgnoreExtraProperties

/**
 * Represents a single message within a chat conversation.
 *
 * This data class serves as the primary model for chat messages in the application,
 * designed for seamless serialization and deserialization with Firebase Realtime Database.
 * It supports both text and image messages, reply functionality, and read status tracking.
 *
 * Key features:
 * - Support for text and image message types
 * - Reply-to-message functionality with complete context
 * - Read status tracking (sent, delivered, read)
 * - Firebase-compatible with no-argument constructor
 * - Utility methods for common operations
 * - Comprehensive message metadata storage
 * - Timestamp-based ordering and filtering
 *
 * The class includes reply information to maintain conversation context and
 * read status information to provide delivery confirmations.
 *
 * @property id A unique identifier for the message, typically generated by Firebase
 * @property senderId The unique ID of the user who sent the message
 * @property receiverId The unique ID of the user who is intended to receive the message
 * @property message The main text content of the message, or caption for image messages
 * @property timestamp The server-side timestamp indicating when the message was created, in milliseconds
 * @property imageUrl The URL of the image, only present if [messageType] is [MessageType.IMAGE]
 * @property messageType The type of the message, either [MessageType.TEXT] or [MessageType.IMAGE]
 * @property readStatus The delivery and read status of the message, see [ReadStatus]
 * @property replyToMessageId The ID of the message this message is replying to, null if not a reply
 * @property replyToMessage The content of the message being replied to, for display purposes
 * @property replyToSenderId The ID of the sender of the message being replied to
 * @property replyToMessageType The type of the message being replied to
 * @property replyToImageUrl The URL of the image being replied to, if it's an image message
 */
@IgnoreExtraProperties
data class ChatMessage(
    val id: String = "",
    val senderId: String = "",
    val receiverId: String = "",
    val message: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val imageUrl: String? = null,
    val messageType: MessageType = MessageType.TEXT,
    val readStatus: ReadStatus = ReadStatus.SENT,
    val replyToMessageId: String? = null,
    val replyToMessage: String? = null,
    val replyToSenderId: String? = null,
    val replyToMessageType: MessageType? = null,
    val replyToImageUrl: String? = null
) {
    /**
     * No-argument constructor required by Firebase for deserialization.
     * Initializes all properties with their default values to ensure
     * compatibility with Firebase's object mapping system.
     */
    constructor() : this(
        "",
        "",
        "",
        "",
        0L,
        null,
        MessageType.TEXT,
        ReadStatus.SENT,
        null,
        null,
        null,
        null,
        null
    )

    /**
     * Checks if this message was sent by a specific user.
     *
     * This convenience method provides a clear way to determine message ownership,
     * which is essential for UI rendering and permission checks.
     *
     * @param userId The ID of the user to check against the sender of this message
     * @return true if the [senderId] matches the provided [userId], false otherwise
     */
    fun isSentBy(userId: String): Boolean = senderId == userId

    /**
     * Checks if this message was intended for a specific user.
     *
     * This convenience method helps determine if a user is the intended recipient
     * of a message, useful for filtering and permission checks.
     *
     * @param userId The ID of the user to check against the receiver of this message
     * @return true if the [receiverId] matches the provided [userId], false otherwise
     */
    fun isReceivedBy(userId: String): Boolean = receiverId == userId

    /**
     * Checks if this message is a reply to another message.
     *
     * This convenience method determines whether the message has reply context,
     * which affects UI rendering and conversation flow.
     *
     * @return true if this message has reply information (replyToMessageId is not null), false otherwise
     */
    fun isReply(): Boolean = replyToMessageId != null
}

/**
 * Defines the type of content a [ChatMessage] holds.
 *
 * This enum categorizes messages based on their primary content type,
 * enabling appropriate rendering and handling in the UI layer.
 */
enum class MessageType {
    /** The message contains only plain text content */
    TEXT,

    /** The message contains an image, referenced by [ChatMessage.imageUrl] */
    IMAGE
}

/**
 * Defines the delivery and read status of a [ChatMessage].
 *
 * This enum tracks the message lifecycle from sending through to being read
 * by the recipient, enabling read receipts and delivery confirmations.
 */
enum class ReadStatus {
    /** The message has been sent from the client but delivery status is unknown */
    SENT,

    /** The message has been delivered to the recipient's device */
    DELIVERED,

    /** The message has been read by the recipient */
    READ
}
